### PR TITLE
Ranking refacto

### PR DESCRIPTION
**Pull request by domi41**

### CODE REVIEW

**Comment by guhur** [comment]
Wow so much modifications! Pretty cool!!! 

However, I am feeling a bit overwhelmed by it... I am trying to setup a CI with circleci, which would ease the review by clearly identify the tests. 

Also, I see you are writing SQL requests by hand. I find it quite unusual, I tend to use an ORM for that. I guess you have some reasons for by passing it, right?

**Comment by guhur** [comment]
Oh I see that you already did a gitlab CI file. How can we integrate it?

**Comment by domi41** [comment]
Ok ; everything out of `lib/` was not supposed to be a part of this MR.

The lone SQL query is actually a DQL query. It is interpreted by our ORM.  Not sure why I used direct SQL-like syntax in this instance (it's a simple COUNT).

The point of this MR is to showcase the new PHP JM lib in `lib/` before we move it to its own repo.

Relevant tests are in `lib/mieuxvoter/Test`.

This whole project so far is tested by `./vendor/bin/behat`.
Except for the files in `lib`, since they are meant to go in an external PHP lib.

**Comment by domi41** [comment]
I've added the (last?) missing piece (default grades).

Should I rename the `MajorityJudgmentResolver` into `MajorityJudgmentDeliberator` ?

(and its method from `resolve` to `deliberate`)

I think the second one is less ambiguous, since `Resolver` is already used by the Symfony ecosystem for something else.
What do you think ?

I tried Ranking, Tallier, TallyBot…  Deliberator feels adequate.

The name is important , since it is the main entrypoint of the library.

---

Regarding CircleCI, I'm not familiar with its config file, but it should resemble the github and gitlab one.

The command to run in order to test the lib is:

```
$ ./vendor/bin/phpunit lib/
```

It probably will be `./` instead of `lib/` once the lib is in its own repo.

**Comment by domi41** [comment]
At this point the used mj lib is an external PHP dependency, [`mj-library-php`](https://github.com/MieuxVoter/mj-library-php).

**Pull request merged**
